name: Java CI with Maven and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: 'pranesh1998/java-maven-app:latest'
      CONTAINER_NAME: 'my-java-maven-app-container'
      HOST_PORT: '8083'
      CONTAINER_PORT: '8080'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean package 

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t $DOCKER_IMAGE_NAME .

    - name: Push Docker image
      run: docker push $DOCKER_IMAGE_NAME

    - name: Deploy Docker container
      run: |
        # Pull the Docker image
        docker pull $DOCKER_IMAGE_NAME

        # Stop and remove the container if it exists
        if [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
        fi

        # Run the Docker container
        docker run -d --name $CONTAINER_NAME -p $HOST_PORT:$CONTAINER_PORT $DOCKER_IMAGE_NAME
